![IDAL](https://i.imgur.com/tIKXIG1.jpg)  

#**Máster en Inteligencia Artificial Avanzada y Aplicada:  IA^3**
---


# PyTorch Basico Ejercicios - SOLUCIONES

En estos ejercicos crearemos algunos tensores y realizaremos operaciones básicos sobre ellos.


### 1. Realiza las importaciones standard
Importa torch and NumPy

In [1]:

import torch
import numpy as np

### 2. Configura una semilla para los generadores de ambos Numpy y Pytorch con el valor "42"
Esto permite reproducir los mismos resultados "aleatorios"

In [2]:
np.random.seed(42)
torch.manual_seed(42); # El punto y como suprime la línea de salida en jupyter

### 3. Crea un NumPy array llamado "arr" que contenga 6 enteros aleatorios entre 0 (incluido) y 5 (excluido)

In [12]:
arr = np.random.randint(0,5,6)
print(arr)

[0 3 1 4 3 0]


### 4. Crea a tensor "x" del array anterior 

In [13]:
x = torch.from_numpy(arr)
print(x)

tensor([0, 3, 1, 4, 3, 0])


In [14]:
print(x.type())

torch.LongTensor


### 5. Cambia el tipo de dato (`dtype`) de x de 'int32' a 'int64'
Nota: 'int64' tambien se puede llamar 'LongTensor'

In [15]:
x = x.type(torch.int32)
# x = x.type(torch.LongTensor)
print(x.type())

torch.IntTensor


### 6. Cambia la forma del tensor a un 3x2 tensor
Hay varias formas de hacer esto

In [16]:
x = x.view(3,2)
# x = x.reshape(3,2)
# x.resize_(3,2)
print(x)

tensor([[0, 3],
        [1, 4],
        [3, 0]], dtype=torch.int32)


### 7. Retorna la columna de la derecha del tensor the right-hand column of tensor x

Atención a la forma de hacerlo 

In [17]:
print(x[:,1:])
# print(x[:,1])

tensor([[3],
        [4],
        [0]], dtype=torch.int32)


In [18]:
print(x[:,1])


tensor([3, 4, 0], dtype=torch.int32)


### 8. Sin cambiar x, retorna un tensor con los valores cuadradaticos de x
Hay varias formas de hacer esto

In [19]:
print(x*x)
# print(x**2)
# print(x.mul(x))
# print(x.pow(2))
# print(torch.mul(x,x))

tensor([[ 0,  9],
        [ 1, 16],
        [ 9,  0]], dtype=torch.int32)


### 9. Crea un tensor "y" con el mismo número de elementos que x, de forma que pueda realizar una multiplicación de matrices.

Utiliza funciones de Pytorch directamente para crear un tensor de enteros aleatorios entre 0 (incluido) y 5 (excluido). 

Ten en cuenta qué forma debe tener para hacer la multiplicación de matrices...

In [ ]:
y = torch.randint(0,5,(2,3))
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Realiza el producto de matrices entre x e y

In [ ]:
print(x.mm(y))

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Enhorabuena! Vamos calentando motores...

## Fin del Notebook

Referencias y modelos empleados para el Notebook: 

*   Documentación de [Pytorch](https://pytorch.org/docs/stable/index.html) 
*   [PyTorch Tutorial for Deep Learning Researchers](https://github.com/yunjey/pytorch-tutorial) by Yunjey Choi
*   [FastAI](https://www.fast.ai/) development notebooks by Jeremy Howard.
*   Documentación y cursos en [Pierian Data](https://www.pieriandata.com/)
