<a href="https://colab.research.google.com/github/SoniaPMi/AI-3-PyTorch/blob/main/CNN_tests_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import numpy as np
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# Convolución 1D

In [11]:
input_id = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=torch.float)

In [12]:
input_1d = input_id.unsqueeze(0).unsqueeze(0)
input_1d.shape

torch.Size([1, 1, 10])

In [14]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=1)

print("cnn1d_1: \n")
print(cnn1d_1(input_1d).shape, "\n")
print(cnn1d_1(input_1d))

cnn1d_1: 

torch.Size([1, 1, 8]) 

tensor([[[1.8322, 2.1240, 2.4159, 2.7077, 2.9996, 3.2914, 3.5833, 3.8751]]],
       grad_fn=<SqueezeBackward1>)


In [16]:
cnn2d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=2)
#stride a 2, la mitad de resultados
print("cnn2d_1: \n")
print(cnn2d_1(input_1d).shape, "\n")
print(cnn2d_1(input_1d))

cnn2d_1: 

torch.Size([1, 1, 4]) 

tensor([[[-0.5310, -1.4648, -2.3985, -3.3323]]], grad_fn=<SqueezeBackward1>)


In [17]:
cnn2d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=2, stride=1)
#stride a 2, la mitad de resultados
print("cnn2d_1: \n")
print(cnn2d_1(input_1d).shape, "\n")
print(cnn2d_1(input_1d))

cnn2d_1: 

torch.Size([1, 1, 9]) 

tensor([[[ 2.6269,  3.9496,  5.2724,  6.5951,  7.9178,  9.2406, 10.5633,
          11.8861, 13.2088]]], grad_fn=<SqueezeBackward1>)


In [18]:
cnn2d_1 = nn.Conv1d(in_channels=1, out_channels=5, kernel_size=3, stride=1)
#stride a 2, la mitad de resultados
print("cnn2d_1: \n")
print(cnn2d_1(input_1d).shape, "\n")
print(cnn2d_1(input_1d))

cnn2d_1: 

torch.Size([1, 5, 8]) 

tensor([[[ -0.8817,  -0.7522,  -0.6228,  -0.4933,  -0.3638,  -0.2344,  -0.1049,
            0.0246],
         [ -0.1606,  -0.0189,   0.1229,   0.2646,   0.4063,   0.5481,   0.6898,
            0.8316],
         [ -1.2346,  -1.6351,  -2.0357,  -2.4362,  -2.8368,  -3.2373,  -3.6379,
           -4.0385],
         [ -0.4953,  -0.4664,  -0.4375,  -0.4087,  -0.3798,  -0.3509,  -0.3221,
           -0.2932],
         [ -2.5511,  -3.7643,  -4.9774,  -6.1905,  -7.4036,  -8.6167,  -9.8299,
          -11.0430]]], grad_fn=<SqueezeBackward1>)


In [ ]:
cnn2d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=1)
#stride a 2, la mitad de resultados
print("cnn2d_1: \n")
print(cnn2d_1(input_1d).shape, "\n")
print(cnn2d_1(input_1d))

#Convolución 2D

In [19]:
input_2d = torch.tensor([[1,2,3,4,5], [6,7,8,9,10]], dtype = torch.float)

In [20]:
input_2d = input_2d.unsqueeze(0)
input_2d.shape

torch.Size([1, 2, 5])

In [28]:
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=1)

print("input_2d: \n")
print(cnn1d_5(input_2d).shape, "\n")
print(cnn1d_5(input_2d))

input_2d: 

torch.Size([1, 1, 3]) 

tensor([[[-0.4446, -0.6032, -0.7618]]], grad_fn=<SqueezeBackward1>)


In [34]:
#Aumentar Stride
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=2)

print("cnn2d_1: \n")
print(cnn1d_5(input_2d).shape, "\n")
print(cnn1d_5(input_2d))

cnn2d_1: 

torch.Size([1, 1, 2]) 

tensor([[[-5.2405, -6.6183]]], grad_fn=<SqueezeBackward1>)


In [ ]:
'''
- stride=2
- kernel_size=2
- out_channels=5
- padding=1

In [29]:
#cambiar Kerner
cnn1d_7 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=2, stride=1)

print("input_2d: \n")
print(cnn1d_7(input_2d).shape, "\n")
print(cnn1d_7(input_2d))

input_2d: 

torch.Size([1, 1, 4]) 

tensor([[[0.3984, 0.4642, 0.5300, 0.5959]]], grad_fn=<SqueezeBackward1>)


In [30]:
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=5, kernel_size=3, stride=1)

print("input_2d: \n")
print(cnn1d_5(input_2d).shape, "\n")
print(cnn1d_5(input_2d))

input_2d: 

torch.Size([1, 5, 3]) 

tensor([[[ 7.5019e-01,  4.9095e-01,  2.3172e-01],
         [ 6.3000e-01,  6.4434e-01,  6.5867e-01],
         [ 3.8812e-02,  2.1958e-04, -3.8373e-02],
         [-3.9295e+00, -4.9596e+00, -5.9898e+00],
         [ 3.4925e-01,  1.4921e-01, -5.0818e-02]]], grad_fn=<SqueezeBackward1>)


In [31]:
#padding
cnn1d_ = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=1, padding = 1)

print("input_2d: \n")
print(cnn1d_5(input_2d).shape, "\n")
print(cnn1d_5(input_2d))

input_2d: 

torch.Size([1, 5, 3]) 

tensor([[[ 7.5019e-01,  4.9095e-01,  2.3172e-01],
         [ 6.3000e-01,  6.4434e-01,  6.5867e-01],
         [ 3.8812e-02,  2.1958e-04, -3.8373e-02],
         [-3.9295e+00, -4.9596e+00, -5.9898e+00],
         [ 3.4925e-01,  1.4921e-01, -5.0818e-02]]], grad_fn=<SqueezeBackward1>)


In [ ]:
######

In [47]:
input_2d_img = torch.tensor([[[1,2,3,4,5,6,7,8,9,10],
                              [1,2,3,4,5,6,7,8,9,10],
                              [1,2,3,4,5,6,7,8,9,10]],
                              [[1,2,3,4,5,6,7,8,9,10],
                              [1,2,3,4,5,6,7,8,9,10],
                              [1,2,3,4,5,6,7,8,9,10]],
                              [[1,2,3,4,5,6,7,8,9,10],
                              [1,2,3,4,5,6,7,8,9,10],
                              [1,2,3,4,5,6,7,8,9,10]]],
                              dtype = torch.float)

In [48]:
input_2d_img = input_2d_img.unsqueeze(0)
input_2d_img.shape

torch.Size([1, 3, 3, 10])

In [49]:
cnn2d_1 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=3, stride=1)

print("input_2d_img: \n")
print(cnn2d_1(input_2d_img).shape, "\n")
print(cnn2d_1(input_2d_img))

input_2d_img: 

torch.Size([1, 1, 1, 8]) 

tensor([[[[-0.1855, -0.4731, -0.7606, -1.0482, -1.3358, -1.6234, -1.9110,
           -2.1985]]]], grad_fn=<ThnnConv2DBackward0>)
